// packages/design-mobile/src/components/NDurationCalendar/NDurationCalendar.tsx
import React, { useEffect, useState } from 'react'
import { View, Text, TouchableOpacity, StyleSheet, type TextStyle, type ViewStyle } from 'react-native'
import { theme } from '../../theme'

export interface CalDate {
  year: number
  month: number
  day: number
}

export interface NDurationCalendarProps {
  value?: CalDate | null
  onChange?: (value: CalDate) => void
  /** 시작일 선택 시 duration 일 뒤까지 range 하이라이트 */
  duration?: number
  today?: CalDate
  minDate?: CalDate
}

const DOW = ['일', '월', '화', '수', '목', '금', '토']

function fallbackToday(): CalDate {
  const d = new Date()
  return { year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate() }
}
const toDate = (c: CalDate) => new Date(c.year, c.month - 1, c.day)
const sameDay = (a: Date, b: Date) =>
  a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate()

interface Cell {
  key: string
  day: number
  year: number
  month: number
  dim: boolean
  disabled: boolean
  isToday: boolean
  isStart: boolean
  isEnd: boolean
  inRange: boolean
}

/**
 * 시작일 선택 + duration 자동 range 캘린더 — design-vue NDurationCalendar 의 RN 포팅.
 * 과거 (minDate 이전) disable, 이전월 spillover 는 dim 처리.
 */
export function NDurationCalendar({
  value = null,
  onChange,
  duration = 0,
  today,
  minDate,
}: NDurationCalendarProps) {
  const todayC = today ?? fallbackToday()
  const minC = minDate ?? todayC

  const initial = value ?? todayC
  const [view, setView] = useState<{ year: number; month: number }>({
    year: initial.year,
    month: initial.month,
  })

  useEffect(() => {
    if (value && (value.year !== view.year || value.month !== view.month)) {
      setView({ year: value.year, month: value.month })
    }
    // 외부에서 value 가 다른 달로 바뀔 때만 view 를 따라감
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value?.year, value?.month])

  const { year: y, month: m } = view
  const firstDow = new Date(y, m - 1, 1).getDay()
  const daysInMonth = new Date(y, m, 0).getDate()
  const prevDays = new Date(y, m - 1, 0).getDate()

  const selectedDate = value ? toDate(value) : null
  const endDate = selectedDate ? new Date(selectedDate) : null
  if (endDate && duration > 0) endDate.setDate(endDate.getDate() + duration)
  const todayD = toDate(todayC)
  const minD = toDate(minC)

  const cells: Cell[] = []
  const push = (year: number, month: number, day: number, dim: boolean) => {
    const cellDate = new Date(year, month - 1, day)
    const before = cellDate < minD
    cells.push({
      key: `${year}-${month}-${day}`,
      day,
      year,
      month,
      dim,
      disabled: dim || before,
      isToday: !dim && sameDay(cellDate, todayD),
      isStart: !!selectedDate && sameDay(cellDate, selectedDate),
      isEnd: !!endDate && sameDay(cellDate, endDate),
      inRange: !!selectedDate && !!endDate && cellDate >= selectedDate && cellDate <= endDate,
    })
  }

  for (let i = 0; i < firstDow; i++) {
    const d = prevDays - (firstDow - 1 - i)
    push(m === 1 ? y - 1 : y, m === 1 ? 12 : m - 1, d, true)
  }
  for (let d = 1; d <= daysInMonth; d++) push(y, m, d, false)
  let nx = 1
  while ((firstDow + daysInMonth + nx - 1) % 7 !== 0) {
    push(m === 12 ? y + 1 : y, m === 12 ? 1 : m + 1, nx, true)
    nx++
  }

  const canPrev = new Date(y, m - 1, 0) >= minD

  const prevMonth = () =>
    setView(({ year, month }) => (month === 1 ? { year: year - 1, month: 12 } : { year, month: month - 1 }))
  const nextMonth = () =>
    setView(({ year, month }) => (month === 12 ? { year: year + 1, month: 1 } : { year, month: month + 1 }))

  const cellViewStyle = (c: Cell): ViewStyle[] => {
    const s: ViewStyle[] = [styles.cell]
    if (c.inRange && !c.dim) {
      if (c.isStart) s.push(styles.cellStart)
      else if (c.isEnd) s.push(styles.cellEnd)
      else s.push(styles.cellRange)
    } else if (c.isToday && !c.isStart) {
      s.push(styles.cellToday)
    }
    return s
  }

  const cellTextStyle = (c: Cell, dowIdx: number): TextStyle[] => {
    const s: TextStyle[] = [styles.cellText]
    if (c.dim || (c.disabled && !c.isStart)) s.push(styles.cellTextDisabled)
    else if (dowIdx === 0) s.push(styles.cellTextSun)
    else if (dowIdx === 6) s.push(styles.cellTextSat)
    if (c.isStart && !c.dim) s.push(styles.cellTextStart)
    else if ((c.inRange || c.isEnd) && !c.dim) s.push(styles.cellTextRange)
    return s
  }

  return (
    <View>
      <View style={styles.head}>
        <TouchableOpacity
          style={[styles.nav, !canPrev && styles.navDisabled]}
          onPress={prevMonth}
          disabled={!canPrev}
          accessibilityLabel="이전 달"
        >
          <Text style={styles.navGlyph}>‹</Text>
        </TouchableOpacity>
        <Text style={styles.title}>
          {y}년 {m}월
        </Text>
        <TouchableOpacity style={styles.nav} onPress={nextMonth} accessibilityLabel="다음 달">
          <Text style={styles.navGlyph}>›</Text>
        </TouchableOpacity>
      </View>

      <View style={styles.week}>
        {DOW.map((d, i) => (
          <Text
            key={d}
            style={[styles.wday, i === 0 && styles.cellTextSun, i === 6 && styles.cellTextSat]}
          >
            {d}
          </Text>
        ))}
      </View>

      <View style={styles.grid}>
        {cells.map((c, i) => (
          <TouchableOpacity
            key={c.key}
            style={styles.cellWrap}
            disabled={c.disabled}
            onPress={() => onChange?.({ year: c.year, month: c.month, day: c.day })}
            activeOpacity={0.6}
          >
            <View style={cellViewStyle(c)}>
              <Text style={cellTextStyle(c, i % 7)}>{c.day}</Text>
            </View>
          </TouchableOpacity>
        ))}
      </View>
    </View>
  )
}

const CELL = 38

const styles = StyleSheet.create({
  head: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  title: {
    fontSize: theme.fontSize.base,
    fontWeight: '700',
    color: theme.colors.neutral[900],
  },
  nav: {
    width: 34,
    height: 34,
    borderRadius: theme.radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.neutral[50],
  },
  navDisabled: {
    opacity: 0.35,
  },
  navGlyph: {
    fontSize: 20,
    lineHeight: 22,
    color: theme.colors.neutral[600],
  },
  week: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  wday: {
    flex: 1,
    textAlign: 'center',
    fontSize: theme.fontSize.xs,
    fontWeight: '600',
    color: theme.colors.neutral[400],
    paddingVertical: 4,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  cellWrap: {
    width: '14.2857%',
    alignItems: 'center',
    paddingVertical: 2,
  },
  cell: {
    width: CELL,
    height: CELL,
    borderRadius: theme.radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellToday: {
    borderWidth: 1.5,
    borderColor: theme.colors.primary[300],
  },
  cellStart: {
    backgroundColor: theme.colors.primary[500],
  },
  cellEnd: {
    backgroundColor: theme.colors.primary[100],
  },
  cellRange: {
    backgroundColor: theme.colors.primary[50],
  },
  cellText: {
    fontSize: theme.fontSize.sm,
    fontWeight: '500',
    color: theme.colors.neutral[800],
  },
  cellTextDisabled: {
    color: theme.colors.neutral[300],
  },
  cellTextSun: {
    color: theme.colors.error[500],
  },
  cellTextSat: {
    color: theme.colors.info[500],
  },
  cellTextStart: {
    color: theme.colors.white,
    fontWeight: '700',
  },
  cellTextRange: {
    color: theme.colors.primary[700],
    fontWeight: '600',
  },
})

// packages/design-vue/src/components/NDurationCalendar/NDurationCalendar.vue
<template>
  <div class="n-duration-calendar">
    <header class="n-duration-calendar__head">
      <button
        type="button"
        class="n-duration-calendar__nav"
        :disabled="!canPrev"
        :aria-label="'이전 달'"
        @click="prevMonth"
      >
        <svg
          width="18"
          height="18"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M15 18l-6-6 6-6" />
        </svg>
      </button>
      <div class="n-duration-calendar__title">{{ view.year }}년 {{ view.month }}월</div>
      <button
        type="button"
        class="n-duration-calendar__nav"
        :aria-label="'다음 달'"
        @click="nextMonth"
      >
        <svg
          width="18"
          height="18"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M9 18l6-6-6-6" />
        </svg>
      </button>
    </header>

    <div class="n-duration-calendar__week">
      <div v-for="(d, i) in dow" :key="i" :class="['n-duration-calendar__wday', dowClass(i)]">
        {{ d }}
      </div>
    </div>

    <div class="n-duration-calendar__grid">
      <button
        v-for="(cell, i) in cells"
        :key="i"
        type="button"
        :class="cell.cls"
        :disabled="cell.disabled"
        @click="cell.clickable ? selectDay(cell.year, cell.month, cell.day) : null"
      >
        {{ cell.day }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watchEffect } from 'vue'

export interface CalDate {
  year: number
  month: number
  day: number
}

export interface NDurationCalendarProps {
  modelValue?: CalDate | null
  duration?: number
  today?: CalDate
  minDate?: CalDate
}

const props = withDefaults(defineProps<NDurationCalendarProps>(), {
  modelValue: null,
  duration: 0,
  today: undefined,
  minDate: undefined,
})

const emit = defineEmits<{
  'update:modelValue': [value: CalDate]
}>()

const dow = ['일', '월', '화', '수', '목', '금', '토']
const dowClass = (i: number) => {
  if (i === 0) return 'n-duration-calendar__wday--sun'
  if (i === 6) return 'n-duration-calendar__wday--sat'
  return ''
}

function fallbackToday(): CalDate {
  const d = new Date()
  return { year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate() }
}
const todayRef = computed<CalDate>(() => props.today ?? fallbackToday())
const minDate = computed<CalDate>(() => props.minDate ?? todayRef.value)
const toDate = (c: CalDate) => new Date(c.year, c.month - 1, c.day)
const sameDay = (a: Date, b: Date) =>
  a.getFullYear() === b.getFullYear() &&
  a.getMonth() === b.getMonth() &&
  a.getDate() === b.getDate()

const initialView = computed<CalDate>(() => {
  const m = props.modelValue ?? todayRef.value
  return { year: m.year, month: m.month, day: 1 }
})

const view = ref<CalDate>({ ...initialView.value })

watchEffect(() => {
  // when modelValue changes outside, follow the view if the month is different
  if (
    props.modelValue &&
    (props.modelValue.year !== view.value.year || props.modelValue.month !== view.value.month)
  ) {
    view.value = { year: props.modelValue.year, month: props.modelValue.month, day: 1 }
  }
})

const cells = computed(() => {
  const y = view.value.year
  const m = view.value.month
  const firstDow = new Date(y, m - 1, 1).getDay()
  const daysInMonth = new Date(y, m, 0).getDate()
  const prevDays = new Date(y, m - 1, 0).getDate()
  const selectedDate = props.modelValue ? toDate(props.modelValue) : null
  const endDate = selectedDate ? new Date(selectedDate) : null
  if (endDate && props.duration > 0) endDate.setDate(endDate.getDate() + props.duration)
  const today = toDate(todayRef.value)
  const minD = toDate(minDate.value)

  function classFor(cellDate: Date, dim: boolean) {
    const before = cellDate < minD
    const isToday = sameDay(cellDate, today)
    const isStart = selectedDate && sameDay(cellDate, selectedDate)
    const isEnd = endDate && sameDay(cellDate, endDate)
    const inRange = selectedDate && endDate && cellDate >= selectedDate && cellDate <= endDate

    const parts: string[] = ['n-duration-calendar__cell']
    if (dim) parts.push('n-duration-calendar__cell--dim')
    if (!dim && before && !isStart) parts.push('n-duration-calendar__cell--disabled')
    if (!dim && isToday && !isStart) parts.push('n-duration-calendar__cell--today')
    if (inRange) {
      if (isStart)
        parts.push('n-duration-calendar__cell--selected', 'n-duration-calendar__cell--range-start')
      else if (isEnd)
        parts.push('n-duration-calendar__cell--range', 'n-duration-calendar__cell--range-end')
      else parts.push('n-duration-calendar__cell--range')
    }
    return parts.join(' ')
  }

  const list: Array<{
    cls: string
    day: number
    year: number
    month: number
    clickable: boolean
    disabled: boolean
  }> = []

  // previous month leading (dim)
  for (let i = 0; i < firstDow; i++) {
    const d = prevDays - (firstDow - 1 - i)
    const cellDate = new Date(y, m - 2, d)
    list.push({
      cls: classFor(cellDate, true),
      day: d,
      year: m === 1 ? y - 1 : y,
      month: m === 1 ? 12 : m - 1,
      clickable: false,
      disabled: true,
    })
  }
  // current month
  for (let d = 1; d <= daysInMonth; d++) {
    const cellDate = new Date(y, m - 1, d)
    const before = cellDate < minD
    list.push({
      cls: classFor(cellDate, false),
      day: d,
      year: y,
      month: m,
      clickable: !before,
      disabled: before,
    })
  }
  // next month trailing
  let nx = 1
  while ((firstDow + daysInMonth + nx - 1) % 7 !== 0) {
    const cellDate = new Date(y, m, nx)
    list.push({
      cls: classFor(cellDate, true),
      day: nx,
      year: m === 12 ? y + 1 : y,
      month: m === 12 ? 1 : m + 1,
      clickable: false,
      disabled: true,
    })
    nx++
  }
  return list
})

const canPrev = computed(() => {
  const prevLast = new Date(view.value.year, view.value.month - 1, 0)
  return prevLast >= toDate(minDate.value)
})

function selectDay(year: number, month: number, day: number) {
  view.value = { year, month, day: 1 }
  emit('update:modelValue', { year, month, day })
}

function prevMonth() {
  let { year, month } = view.value
  month--
  if (month < 1) {
    month = 12
    year--
  }
  view.value = { year, month, day: 1 }
}

function nextMonth() {
  let { year, month } = view.value
  month++
  if (month > 12) {
    month = 1
    year++
  }
  view.value = { year, month, day: 1 }
}
</script>

<style scoped>
.n-duration-calendar {
  font-family: var(--font-fontFamily-sans, sans-serif);
}

.n-duration-calendar__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.n-duration-calendar__title {
  font-size: 15px;
  font-weight: 700;
  color: var(--color-neutral-900, #171717);
}

.n-duration-calendar__nav {
  width: 34px;
  height: 34px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: 0;
  border-radius: var(--radius-full, 9999px);
  background: transparent;
  color: var(--color-neutral-500, #737373);
  cursor: pointer;
  transition:
    background 160ms ease,
    color 160ms ease;
}
.n-duration-calendar__nav:hover:not(:disabled) {
  background: var(--color-neutral-100, #f5f5f5);
  color: var(--color-neutral-900, #171717);
}
.n-duration-calendar__nav:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.n-duration-calendar__week {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  margin-bottom: 8px;
}
.n-duration-calendar__wday {
  text-align: center;
  font-size: 11px;
  font-weight: 600;
  color: var(--color-neutral-400, #a3a3a3);
  padding: 4px 0;
}
.n-duration-calendar__wday--sun {
  color: var(--color-error-500, #ef4444);
}
.n-duration-calendar__wday--sat {
  color: var(--color-info-500, #3b82f6);
}

.n-duration-calendar__grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 2px;
}

.n-duration-calendar__cell {
  height: 42px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  font-weight: 500;
  color: var(--color-neutral-900, #171717);
  background: transparent;
  border: 0;
  border-radius: var(--radius-xl, 0.75rem);
  cursor: pointer;
  position: relative;
  transition:
    background 120ms ease,
    color 120ms ease;
}
.n-duration-calendar__cell:hover:not(:disabled) {
  background: var(--color-neutral-100, #f5f5f5);
}
.n-duration-calendar__cell--dim {
  color: var(--color-neutral-300, #d4d4d4);
  cursor: default;
}
.n-duration-calendar__cell--dim:hover {
  background: transparent;
}
.n-duration-calendar__cell--disabled {
  color: var(--color-neutral-300, #d4d4d4);
  cursor: not-allowed;
}
.n-duration-calendar__cell--disabled:hover {
  background: transparent;
}
.n-duration-calendar__cell--today {
  color: var(--color-primary-500, #6239ff);
  font-weight: 700;
}
.n-duration-calendar__cell--today::after {
  content: '';
  position: absolute;
  bottom: 6px;
  width: 4px;
  height: 4px;
  border-radius: var(--radius-full, 9999px);
  background: var(--color-primary-500, #6239ff);
}
.n-duration-calendar__cell--range {
  background: var(--color-primary-50, #f1edff);
  color: var(--color-primary-600, #5025e8);
  border-radius: 0;
}
.n-duration-calendar__cell--range-start {
  border-radius: var(--radius-xl, 0.75rem) 0 0 var(--radius-xl, 0.75rem);
}
.n-duration-calendar__cell--range-end {
  border-radius: 0 var(--radius-xl, 0.75rem) var(--radius-xl, 0.75rem) 0;
}
.n-duration-calendar__cell--selected {
  background: var(--color-primary-500, #6239ff);
  color: var(--color-neutral-0, #ffffff) !important;
  font-weight: 700;
}
.n-duration-calendar__cell--selected.n-duration-calendar__cell--range-start {
  border-radius: var(--radius-xl, 0.75rem);
}
.n-duration-calendar__cell--selected::after {
  background: var(--color-neutral-0, #ffffff);
}
</style>
