// apps/client/app/pages/verify/[orderId].vue
<script setup lang="ts">
import {
  NStepProgress,
  NPageHeading,
  NInfoChip,
  NInput,
  NTrustNote,
  NButton,
  NAlertDialog,
  NLoaderDialog,
} from '@imjohnkoo/design-vue'
import { useOrderStore } from '~/stores/order'
import { useApi } from '~/composables/useApi'
import { formatPhoneNumber, isValidPhoneNumber } from '~/utils/formatter'

const route = useRoute()
const router = useRouter()
const orderStore = useOrderStore()
const api = useApi()

const orderId = computed(() => Number(route.params.orderId))

const fullName = ref('')
const phoneNumber = ref('')
const errors = ref<{ fullName?: string; phoneNumber?: string }>({})

const isSubmitting = ref(false)
const isAlertVisible = ref(false)
const isCancelledOrderVisible = ref(false)
const isServerErrorVisible = ref(false)

watch(phoneNumber, (val) => {
  const formatted = formatPhoneNumber(val)
  if (formatted !== val) phoneNumber.value = formatted
})

const validate = () => {
  errors.value = {}
  if (!fullName.value.trim()) errors.value.fullName = '이름을 입력해주세요.'
  if (!phoneNumber.value) {
    errors.value.phoneNumber = '전화번호를 입력해주세요.'
  } else if (!isValidPhoneNumber(phoneNumber.value)) {
    errors.value.phoneNumber = '유효하지 않은 전화번호 형식입니다.'
  }
  return Object.keys(errors.value).length === 0
}

const onSubmit = async () => {
  if (!validate()) return
  isSubmitting.value = true
  await new Promise((resolve) => setTimeout(resolve, 1200))
  try {
    const response = await api.verifyOrder({
      fullName: fullName.value,
      phoneNumber: phoneNumber.value,
      orderId: orderId.value,
    })
    const { verified, cancelled, details } = response
    if (verified && !cancelled) {
      orderStore.setOrders(details || [])
      router.push(`/details/${orderId.value}`)
    } else if (verified && cancelled) {
      isCancelledOrderVisible.value = true
    } else {
      isAlertVisible.value = true
    }
  } catch (error) {
    console.error(error)
    isServerErrorVisible.value = true
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <div class="verify-page">
    <div class="verify-page__top">
      <NStepProgress :step="1" :total="4" label="본인 확인" />
    </div>

    <div class="verify-page__heading">
      <NPageHeading
        eyebrow="eSIM QR 코드 발급"
        :title="`주문하신 분이\n맞는지 확인할게요`"
        :description="`주문 시 입력하신 이름과 전화번호를\n그대로 입력해 주세요.`"
      />
    </div>

    <div class="verify-page__chip">
      <NInfoChip label="주문번호" :value="String(orderId)">
        <template #icon>
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <rect x="3" y="4" width="18" height="16" rx="2" />
            <path d="M8 2v4M16 2v4M3 10h18" />
          </svg>
        </template>
      </NInfoChip>
    </div>

    <form class="verify-page__form" @submit.prevent="onSubmit">
      <div class="verify-page__field">
        <NInput v-model="fullName" variant="underline" label="이름" :error="!!errors.fullName" />
        <p v-if="errors.fullName" class="verify-page__err">{{ errors.fullName }}</p>
      </div>

      <div class="verify-page__field">
        <NInput
          v-model="phoneNumber"
          variant="underline"
          label="전화번호"
          type="tel"
          :error="!!errors.phoneNumber"
        />
        <p v-if="errors.phoneNumber" class="verify-page__err">{{ errors.phoneNumber }}</p>
      </div>

      <div class="verify-page__note">
        <NTrustNote>
          본인 확인은 주문자와 동일한지 검증하기 위한 용도예요.<br />
          입력한 정보는 안전하게 처리되며, 발급 외 다른 목적으로 사용하지 않아요.
        </NTrustNote>
      </div>

      <div class="verify-page__cta">
        <NButton type="submit" variant="primary" size="xl" full-width :disabled="isSubmitting">
          주문 확인하기
        </NButton>
      </div>
    </form>

    <NLoaderDialog
      v-model="isSubmitting"
      title="주문을 확인하고 있어요"
      description="잠시만 기다려주세요…"
    />

    <NAlertDialog
      v-model="isAlertVisible"
      title="주문번호와 일치하지 않아요"
      color="warning"
      :closable="false"
    >
      <p class="verify-page__dialog-desc">
        주문 시 입력하신 이름과 전화번호를<br />다시 한 번 확인해 주세요.
      </p>
      <template #actions>
        <NButton variant="primary" full-width @click="isAlertVisible = false">
          다시 입력하기
        </NButton>
      </template>
    </NAlertDialog>

    <NAlertDialog
      v-model="isCancelledOrderVisible"
      title="이미 취소된 주문이에요"
      color="warning"
      :closable="false"
    >
      <p class="verify-page__dialog-desc">
        취소된 주문은 발급할 수 없어요.<br />
        스마트스토어에서 새로 주문해 주세요.
      </p>
      <template #actions>
        <NButton variant="primary" full-width @click="isCancelledOrderVisible = false">
          확인
        </NButton>
      </template>
    </NAlertDialog>

    <NAlertDialog
      v-model="isServerErrorVisible"
      title="잠시 후 다시 시도해 주세요"
      color="error"
      :closable="false"
    >
      <p class="verify-page__dialog-desc">
        서버에 일시적인 문제가 발생했어요.<br />
        잠시 후 다시 시도해 주세요.
      </p>
      <template #actions>
        <NButton variant="primary" full-width @click="isServerErrorVisible = false"> 확인 </NButton>
      </template>
    </NAlertDialog>
  </div>
</template>

<style scoped>
.verify-page {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  padding: 20px 24px 32px;
  background: #ffffff;
}

.verify-page__top {
  padding-top: 4px;
}

.verify-page__heading {
  margin-top: 28px;
}

.verify-page__chip {
  margin-top: 18px;
}

.verify-page__form {
  margin-top: 28px;
  display: flex;
  flex-direction: column;
  flex: 1;
}

.verify-page__field {
  margin-top: 12px;
}

.verify-page__field:first-of-type {
  margin-top: 0;
}

.verify-page__err {
  margin: 6px 0 0;
  font-size: 12px;
  color: var(--n-color-error-500, #ef4444);
}

.verify-page__note {
  margin-top: 28px;
}

.verify-page__cta {
  margin-top: auto;
  padding-top: 32px;
}

.verify-page__dialog-desc {
  margin: -6px 0 0;
  font-size: 13px;
  color: #6b7280;
  text-align: center;
  line-height: 1.55;
}
</style>

// apps/mobile/src/app/verify/[orderId].tsx
import { useState } from 'react'
import { StyleSheet, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'

import {
  NAlertDialog,
  NButton,
  NInfoChip,
  NInput,
  NLoaderDialog,
  NPageHeading,
  NStepProgress,
  NTrustNote,
} from '@imjohnkoo/design-mobile'

import { FlowScreen, FlowSpacer } from '@/components/flow-screen'
import { api } from '@/lib/api'
import { formatPhoneNumber, isValidPhoneNumber } from '@/lib/format'
import { useOrderStore } from '@/lib/order-store'

export default function VerifyScreen() {
  const router = useRouter()
  const { orderId: orderIdParam } = useLocalSearchParams<{ orderId: string }>()
  const orderId = Number(orderIdParam)
  const orderStore = useOrderStore()

  const [fullName, setFullName] = useState('')
  const [phoneNumber, setPhoneNumber] = useState('')
  const [errors, setErrors] = useState<{ fullName?: string; phoneNumber?: string }>({})

  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isAlertVisible, setIsAlertVisible] = useState(false)
  const [isCancelledOrderVisible, setIsCancelledOrderVisible] = useState(false)
  const [isServerErrorVisible, setIsServerErrorVisible] = useState(false)

  const validate = () => {
    const next: typeof errors = {}
    if (!fullName.trim()) next.fullName = '이름을 입력해주세요.'
    if (!phoneNumber) {
      next.phoneNumber = '전화번호를 입력해주세요.'
    } else if (!isValidPhoneNumber(phoneNumber)) {
      next.phoneNumber = '유효하지 않은 전화번호 형식입니다.'
    }
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const onSubmit = async () => {
    if (!validate() || isSubmitting) return
    setIsSubmitting(true)
    try {
      const response = await api.verifyOrder({
        fullName: fullName.trim(),
        phoneNumber,
        orderId,
      })
      const { verified, cancelled, details } = response
      if (verified && !cancelled) {
        orderStore.setOrders(details || [])
        router.push({ pathname: '/details/[orderId]', params: { orderId: orderIdParam } })
      } else if (verified && cancelled) {
        setIsCancelledOrderVisible(true)
      } else {
        setIsAlertVisible(true)
      }
    } catch (error) {
      console.error(error)
      setIsServerErrorVisible(true)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <FlowScreen>
      <NStepProgress step={1} total={4} label="본인 확인" />

      <View style={styles.heading}>
        <NPageHeading
          eyebrow="eSIM QR 코드 발급"
          title={'주문하신 분이\n맞는지 확인할게요'}
          description={'주문 시 입력하신 이름과 전화번호를\n그대로 입력해 주세요.'}
        />
      </View>

      <View style={styles.chip}>
        <NInfoChip label="주문번호" value={String(orderId)} />
      </View>

      <View style={styles.form}>
        <NInput
          label="이름"
          value={fullName}
          onChangeText={setFullName}
          error={errors.fullName}
          autoCapitalize="none"
          returnKeyType="next"
        />
        <View style={styles.field}>
          <NInput
            label="전화번호"
            value={phoneNumber}
            onChangeText={(t) => setPhoneNumber(formatPhoneNumber(t))}
            error={errors.phoneNumber}
            keyboardType="phone-pad"
            maxLength={13}
            returnKeyType="done"
            onSubmitEditing={onSubmit}
          />
        </View>
      </View>

      <View style={styles.note}>
        <NTrustNote>
          {'본인 확인은 주문자와 동일한지 검증하기 위한 용도예요.\n입력한 정보는 안전하게 처리되며, 발급 외 다른 목적으로 사용하지 않아요.'}
        </NTrustNote>
      </View>

      <FlowSpacer />

      <View style={styles.cta}>
        <NButton variant="primary" size="xl" fullWidth disabled={isSubmitting} onPress={onSubmit}>
          주문 확인하기
        </NButton>
      </View>

      <NLoaderDialog
        visible={isSubmitting}
        title="주문을 확인하고 있어요"
        description="잠시만 기다려주세요…"
      />

      <NAlertDialog
        visible={isAlertVisible}
        title="주문번호와 일치하지 않아요"
        color="warning"
        closable={false}
        actions={
          <NButton variant="primary" fullWidth onPress={() => setIsAlertVisible(false)}>
            다시 입력하기
          </NButton>
        }
      >
        {'주문 시 입력하신 이름과 전화번호를\n다시 한 번 확인해 주세요.'}
      </NAlertDialog>

      <NAlertDialog
        visible={isCancelledOrderVisible}
        title="이미 취소된 주문이에요"
        color="warning"
        closable={false}
        actions={
          <NButton variant="primary" fullWidth onPress={() => setIsCancelledOrderVisible(false)}>
            확인
          </NButton>
        }
      >
        {'취소된 주문은 발급할 수 없어요.\n스마트스토어에서 새로 주문해 주세요.'}
      </NAlertDialog>

      <NAlertDialog
        visible={isServerErrorVisible}
        title="잠시 후 다시 시도해 주세요"
        color="error"
        closable={false}
        actions={
          <NButton variant="primary" fullWidth onPress={() => setIsServerErrorVisible(false)}>
            확인
          </NButton>
        }
      >
        {'서버에 일시적인 문제가 발생했어요.\n잠시 후 다시 시도해 주세요.'}
      </NAlertDialog>
    </FlowScreen>
  )
}

const styles = StyleSheet.create({
  heading: {
    marginTop: 28,
  },
  chip: {
    marginTop: 18,
  },
  form: {
    marginTop: 28,
  },
  field: {
    marginTop: 12,
  },
  note: {
    marginTop: 28,
  },
  cta: {
    paddingTop: 32,
  },
})
