// apps/client/app/pages/view-variant/accordion/[orderId].vue
<script setup lang="ts">
import QRCodeVue3 from 'qrcode-vue3'
import {
  NStepProgress,
  NPageHeading,
  NInfoChip,
  NStatusPill,
  NCodeRow,
  NLinkCard,
  NButton,
  NTrustNote,
} from '@imjohnkoo/design-vue'
import { useOrderStore } from '~/stores/order'
import { buildMultiQrSeed } from '~/utils/multi-qr-seed'

const route = useRoute()
const router = useRouter()
const orderStore = useOrderStore()

const orderId = computed(() => Number(route.params.orderId))
const order = computed(() => orderStore.singleOrder)
const openIdx = ref<number>(0) // 첫 esim 만 펼쳐서 시작

const toggle = (idx: number) => {
  openIdx.value = openIdx.value === idx ? -1 : idx
}

const downloadQR = (index: number) => {
  const canvas = document.querySelector(`#qr-acc-${index} canvas`) as HTMLCanvasElement
  if (!canvas) return
  const url = canvas.toDataURL('image/png').replace('image/png', 'image/octet-stream')
  const a = document.createElement('a')
  a.href = url
  a.download = `qr-code-${index + 1}.png`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
}

onMounted(() => {
  orderStore.setSingleOrder(buildMultiQrSeed(6))
})
</script>

<template>
  <div class="vv">
    <NStepProgress :step="4" :total="4" label="발급 완료" />

    <div class="vv__heading">
      <NPageHeading
        eyebrow="Accordion 패턴"
        :title="`리스트에서\n눌러서 펼치기`"
        description="모든 esim 의 상태를 한눈에. 필요한 카드만 펼쳐서 QR 확인."
      />
    </div>

    <div class="vv__chip-row">
      <NInfoChip label="주문번호" :value="String(orderId)" />
      <NInfoChip v-if="order" :value="`${order.planNameKr} · ${order.esims.length}개`" />
    </div>

    <ul v-if="order" class="vv__list">
      <li
        v-for="(esim, idx) in order.esims"
        :key="idx"
        class="vv__row"
        :class="{ 'vv__row--open': openIdx === idx }"
      >
        <button class="vv__row-head" type="button" @click="toggle(idx)">
          <span class="vv__row-head-left">
            <span class="vv__row-num">eSIM {{ idx + 1 }}</span>
            <NStatusPill color="success" dot>발급완료</NStatusPill>
          </span>
          <svg
            class="vv__chev"
            :class="{ 'vv__chev--open': openIdx === idx }"
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2.4"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M6 9l6 6 6-6" />
          </svg>
        </button>

        <div v-show="openIdx === idx" class="vv__row-body">
          <div :id="`qr-acc-${idx}`" class="vv__qr">
            <ClientOnly>
              <QRCodeVue3 :value="esim.activationCode" :width="180" :height="180" :margin="2" />
              <template #fallback>
                <div class="vv__qr-skel" />
              </template>
            </ClientOnly>
          </div>

          <div class="vv__download">
            <NButton variant="secondary" size="sm" @click="downloadQR(idx)"> QR 다운로드 </NButton>
          </div>

          <div class="vv__codes">
            <NCodeRow label="SM-DP+" :value="esim.smdpAddress" />
            <NCodeRow label="활성화 코드" :value="esim.manualCode" />
            <NCodeRow label="LPA 전체" :value="esim.activationCode" />
          </div>
        </div>
      </li>
    </ul>

    <div class="vv__divider"><span>설치 가이드</span></div>

    <div class="vv__guides">
      <NLinkCard
        label="아이폰 설치 가이드"
        sub="iOS · Universal Link"
        href="https://esimmany.super.site"
        external
      />
      <NLinkCard
        label="안드로이드 설치 가이드"
        sub="Galaxy · Pixel · QR 등록"
        href="https://esimmany.super.site"
        external
      />
    </div>

    <div class="vv__notes">
      <NTrustNote>사용 일수는 첫 연결 시점부터 24시간 단위로 차감돼요.</NTrustNote>
      <div style="height: 8px" />
      <NTrustNote>다국가 이심은 자동 로밍으로 그대로 사용할 수 있어요.</NTrustNote>
    </div>

    <div class="vv__back">
      <NButton variant="ghost" size="md" full-width @click="router.push('/view-variant')">
        다른 시안 보기
      </NButton>
    </div>
  </div>
</template>

<style scoped>
.vv {
  padding: 20px 24px 32px;
  background: #ffffff;
}
.vv__heading {
  margin-top: 28px;
}
.vv__chip-row {
  margin-top: 18px;
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.vv__list {
  margin: 22px 0 0;
  padding: 0;
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.vv__row {
  border: 1px solid #eef2f7;
  border-radius: 14px;
  background: #fff;
  overflow: hidden;
  transition:
    box-shadow 160ms ease,
    border-color 160ms ease;
}
.vv__row--open {
  border-color: var(--color-primary-300, #a78bff);
  box-shadow:
    0 1px 2px rgba(15, 23, 42, 0.04),
    0 8px 24px -16px rgba(15, 23, 42, 0.12);
}

.vv__row-head {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 16px;
  background: transparent;
  border: 0;
  cursor: pointer;
}
.vv__row-head-left {
  display: flex;
  align-items: center;
  gap: 10px;
}
.vv__row-num {
  font-size: 14px;
  font-weight: 700;
  color: #0f172a;
  letter-spacing: -0.005em;
}
.vv__chev {
  color: #94a3b8;
  transition: transform 200ms ease;
}
.vv__chev--open {
  transform: rotate(180deg);
  color: var(--color-primary-500, #6239ff);
}

.vv__row-body {
  padding: 4px 16px 18px;
  border-top: 1px solid #f1f5f9;
}
.vv__qr {
  margin: 14px auto 0;
  padding: 10px;
  width: fit-content;
  background: #fff;
  border-radius: 16px;
  border: 1px solid #e5e7eb;
}
.vv__qr-skel {
  width: 180px;
  height: 180px;
  background: #f1f5f9;
  border-radius: 8px;
}
.vv__download {
  display: flex;
  justify-content: center;
  margin-top: 10px;
}
.vv__codes {
  margin-top: 12px;
}

.vv__divider {
  margin: 22px 0 10px;
  display: flex;
  align-items: center;
  gap: 10px;
}
.vv__divider::before,
.vv__divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: #e5e7eb;
}
.vv__divider span {
  font-size: 11.5px;
  font-weight: 600;
  color: #94a3b8;
}

.vv__guides {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.vv__notes {
  margin-top: 20px;
}
.vv__back {
  margin-top: 24px;
}
</style>

// apps/mobile/src/app/view/[orderId].tsx
import { useEffect, useState } from 'react'
import { Linking, Platform, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'
import * as Clipboard from 'expo-clipboard'

import {
  NButton,
  NCard,
  NCodeRow,
  NInfoChip,
  NLinkCard,
  NPageHeading,
  NStatusPill,
  NStepProgress,
  NTrustNote,
} from '@imjohnkoo/design-mobile'

import { FlowScreen } from '@/components/flow-screen'
import { buildAppleUniversalLink } from '@/lib/esim'
import { useOrderStore } from '@/lib/order-store'
import type { Esim } from '@/lib/types'

const GUIDE_URL = 'https://esimmany.super.site'

const copyToClipboard = (value: string) => {
  void Clipboard.setStringAsync(value)
}

function EsimInstallBody({ esim }: { esim: Esim }) {
  const isIos = Platform.OS === 'ios'

  const openInstallLink = () => {
    Linking.openURL(buildAppleUniversalLink(esim.activationCode)).catch((err) =>
      console.warn('Failed to open eSIM universal link', err),
    )
  }

  return (
    <View>
      {isIos ? (
        <>
          <View style={styles.installCta}>
            <NButton variant="primary" size="xl" fullWidth onPress={openInstallLink}>
              eSIM 설치하기
            </NButton>
            <Text style={styles.installHint}>
              iOS 17.4 이상에서 Apple 설치 화면이 바로 열려요.{'\n'}설치가 안 되면 아래 수동 설치
              코드를 이용해 주세요.
            </Text>
          </View>

          <View style={styles.sectionDivider}>
            <Text style={styles.sectionDividerText}>수동 설치 (설정 → 셀룰러 → eSIM 추가)</Text>
          </View>
          <NCodeRow label="SM-DP+ 주소" value={esim.smdpAddress} onCopy={copyToClipboard} />
          <NCodeRow label="활성화 코드" value={esim.manualCode} onCopy={copyToClipboard} />

          <View style={styles.sectionDivider}>
            <Text style={styles.sectionDividerText}>다른 기기 (안드로이드) 에 설치하려면</Text>
          </View>
          <NCodeRow label="LPA 전체" value={esim.activationCode} onCopy={copyToClipboard} />
        </>
      ) : (
        <>
          <Text style={styles.androidGuide}>
            설정 → 연결 → SIM 관리자 → <Text style={styles.androidGuideStrong}>eSIM 추가</Text>{' '}
            에서 아래 코드를 입력해 주세요. (기기에 따라 메뉴 이름이 조금 다를 수 있어요)
          </Text>
          <NCodeRow label="SM-DP+ 주소" value={esim.smdpAddress} onCopy={copyToClipboard} />
          <NCodeRow label="활성화 코드" value={esim.manualCode} onCopy={copyToClipboard} />
          <NCodeRow label="LPA 전체" value={esim.activationCode} onCopy={copyToClipboard} />

          <View style={styles.sectionDivider}>
            <Text style={styles.sectionDividerText}>다른 기기 (아이폰) 에 설치하려면</Text>
          </View>
          <Text style={styles.androidGuide}>
            아이폰 (iOS 17.4+) 의 Safari 에서 설치 링크를 열면 Apple 설치 화면이 바로 열려요. 아래
            버튼으로 링크를 복사해 전달해 주세요.
          </Text>
          <NCodeRow
            label="아이폰 설치 링크"
            value={buildAppleUniversalLink(esim.activationCode)}
            onCopy={copyToClipboard}
          />
        </>
      )}
    </View>
  )
}

export default function ViewScreen() {
  const router = useRouter()
  const { orderId: orderIdParam } = useLocalSearchParams<{ orderId: string }>()
  const orderId = Number(orderIdParam)
  const orderStore = useOrderStore()

  const order = orderStore.singleOrder
  const esims = order?.esims ?? []
  // 다발 발급 케이스: 2개 이상이면 accordion 으로 1번만 펼쳐서 시작
  const isMulti = esims.length >= 2
  const [openIdx, setOpenIdx] = useState(0)

  useEffect(() => {
    if (!order) {
      router.replace({ pathname: '/verify/[orderId]', params: { orderId: orderIdParam } })
    }
    // 최초 진입 가드
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const goHome = () => {
    orderStore.reset()
    router.dismissTo('/')
  }

  return (
    <FlowScreen>
      <NStepProgress step={4} total={4} label="발급 완료" />

      <View style={styles.heading}>
        <NPageHeading
          eyebrow="eSIM QR 코드 발급"
          title={'eSIM 발급이\n완료됐어요'}
          description={'아래 버튼으로 바로 설치해 주세요.\n현지 도착 후 데이터 로밍을 켜면 자동으로 연결돼요.'}
        />
      </View>

      {order && (
        <View style={styles.chipRow}>
          <NInfoChip label="주문번호" value={String(orderId)} />
          <NInfoChip value={order.planNameKr} />
        </View>
      )}

      {order && esims.length > 0 ? (
        <>
          {!isMulti ? (
            <View style={styles.single}>
              <NCard variant="outlined" padding="lg">
                <View style={styles.singleHead}>
                  <NStatusPill color="success" dot>
                    발급완료
                  </NStatusPill>
                </View>
                <EsimInstallBody esim={esims[0]} />
              </NCard>
            </View>
          ) : (
            <View style={styles.list}>
              {esims.map((esim, index) => {
                const open = openIdx === index
                return (
                  <View key={index} style={[styles.row, open && styles.rowOpen]}>
                    <TouchableOpacity
                      style={styles.rowHead}
                      onPress={() => setOpenIdx(open ? -1 : index)}
                      activeOpacity={0.7}
                    >
                      <View style={styles.rowHeadLeft}>
                        <Text style={styles.rowNum}>eSIM {index + 1}</Text>
                        <NStatusPill color="success" dot>
                          발급완료
                        </NStatusPill>
                      </View>
                      <Text style={[styles.chev, open && styles.chevOpen]}>⌄</Text>
                    </TouchableOpacity>
                    {open && (
                      <View style={styles.rowBody}>
                        <EsimInstallBody esim={esim} />
                        {index > 0 && (
                          <Text style={styles.multiHint}>
                            이 eSIM 을 다른 기기에서 사용하려면 코드를 복사해 전달해 주세요.
                          </Text>
                        )}
                      </View>
                    )}
                  </View>
                )
              })}
            </View>
          )}

          <View style={styles.guides}>
            <NLinkCard
              label="아이폰 설치 가이드"
              sub="iOS · Universal Link 자동 설치"
              onPress={() => Linking.openURL(GUIDE_URL)}
            />
            <NLinkCard
              label="안드로이드 설치 가이드"
              sub="Galaxy · Pixel · 수동 등록"
              onPress={() => Linking.openURL(GUIDE_URL)}
            />
          </View>
        </>
      ) : (
        <View style={styles.empty}>
          <Text style={styles.emptyText}>주문 정보를 불러오는 중이에요…</Text>
        </View>
      )}

      <View style={styles.notes}>
        <NTrustNote title="사용 일수는 첫 연결 시점부터 24시간 단위로 차감돼요.">
          {'현지에 도착해 처음 회선이 연결된 순간부터 24시간이 지나면 1일이 차감돼요.'}
        </NTrustNote>
        <View style={styles.noteGap} />
        <NTrustNote title="다국가 이심은 자동 로밍으로 그대로 사용할 수 있어요.">
          {'한 번 개통된 다음에는 포함된 국가들을 오가도 추가 설치나 설정 변경 없이 자동으로 연결돼요.'}
        </NTrustNote>
      </View>

      <View style={styles.back}>
        <NButton variant="ghost" size="md" fullWidth onPress={goHome}>
          처음으로
        </NButton>
      </View>
    </FlowScreen>
  )
}

const styles = StyleSheet.create({
  heading: {
    marginTop: 28,
  },
  chipRow: {
    marginTop: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  single: {
    marginTop: 24,
  },
  singleHead: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  installCta: {
    marginTop: 12,
  },
  installHint: {
    marginTop: 8,
    fontSize: 11.5,
    lineHeight: 17,
    color: '#94a3b8',
    textAlign: 'center',
  },
  sectionDivider: {
    marginTop: 22,
    marginBottom: 6,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 12,
  },
  sectionDividerText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#475569',
  },
  androidGuide: {
    marginTop: 8,
    marginBottom: 6,
    fontSize: 12.5,
    lineHeight: 19,
    color: '#4b5563',
  },
  androidGuideStrong: {
    fontWeight: '700',
    color: '#111827',
  },
  list: {
    marginTop: 24,
    gap: 8,
  },
  row: {
    borderWidth: 1,
    borderColor: '#eef2f7',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  rowOpen: {
    borderColor: '#a78bff',
  },
  rowHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  rowHeadLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowNum: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  chev: {
    fontSize: 18,
    color: '#94a3b8',
    marginTop: -6,
  },
  chevOpen: {
    color: '#6239ff',
    transform: [{ rotate: '180deg' }],
    marginTop: 6,
  },
  rowBody: {
    paddingHorizontal: 16,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  multiHint: {
    marginTop: 12,
    fontSize: 11.5,
    color: '#94a3b8',
  },
  guides: {
    marginTop: 24,
    gap: 8,
  },
  empty: {
    marginTop: 60,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 13,
    color: '#94a3b8',
  },
  notes: {
    marginTop: 24,
  },
  noteGap: {
    height: 8,
  },
  back: {
    marginTop: 28,
  },
})
