// apps/client/app/pages/select-date/[orderId].vue
<script setup lang="ts">
import {
  NStepProgress,
  NPageHeading,
  NInfoChip,
  NFieldCard,
  NHighlightCard,
  NTrustNote,
  NDurationCalendar,
  NBottomSheet,
  NButton,
  NCheckbox,
  NAlertDialog,
  NLoaderDialog,
} from '@imjohnkoo/design-vue'
import type { CalDate } from '@imjohnkoo/design-vue'
import { addDays, format } from 'date-fns'
import { useOrderStore } from '~/stores/order'
import { useApi } from '~/composables/useApi'
import type { Order } from '~/types/order'

const route = useRoute()
const router = useRouter()
const orderStore = useOrderStore()
const api = useApi()

const orderId = computed(() => Number(route.params.orderId))
const order = computed(() => orderStore.singleOrder)

const combinedCountries = computed(() => {
  if (!order.value) return []
  return order.value.planCountriesKr.map((country, index) => ({
    kr: country,
    en: order.value?.planCountriesEng[index] || '',
    iso: order.value?.planCountriesIso[index] || '',
    timeZone: order.value?.timeZones[index] || '',
  }))
})

const selectedCountry = ref<string>('')
const selectedDate = ref<CalDate | null>(null)

const errors = ref<{ country?: string; date?: string }>({})

const isCountrySheetOpen = ref(false)
const isDateSheetOpen = ref(false)
const isSubmitting = ref(false)
const isPolicyAgreed = ref(false)
const isIssueQrCodesVisible = ref(false)
const isNoOrderAlertVisible = ref(false)
const isCancelledOrderVisible = ref(false)
const isConfirmOrderVisible = ref(false)

const formatDate = (d: CalDate | null) => {
  if (!d) return ''
  const dow = ['일', '월', '화', '수', '목', '금', '토']
  const js = new Date(d.year, d.month - 1, d.day)
  return `${d.year}.${String(d.month).padStart(2, '0')}.${String(d.day).padStart(2, '0')} (${dow[js.getDay()]})`
}

const endDateLabel = computed(() => {
  if (!selectedDate.value || !order.value) return ''
  const start = new Date(
    selectedDate.value.year,
    selectedDate.value.month - 1,
    selectedDate.value.day,
  )
  const end = addDays(start, order.value.planDataDuration)
  const dow = ['일', '월', '화', '수', '목', '금', '토']
  return `${format(end, 'yyyy.MM.dd')} (${dow[end.getDay()]})`
})

const startDateLabel = computed(() => formatDate(selectedDate.value))

const countryLabel = computed(() => {
  if (!selectedCountry.value) return ''
  const c = combinedCountries.value.find((c) => c.kr === selectedCountry.value)
  return c ? `${c.kr} · ${c.timeZone}` : selectedCountry.value
})

const getTimeZone = () => {
  const c = combinedCountries.value.find((c) => c.kr === selectedCountry.value)
  return c?.timeZone || 'Asia/Seoul'
}

const onCountrySelect = (kr: string) => {
  selectedCountry.value = kr
  isCountrySheetOpen.value = false
  errors.value.country = undefined
}

const onDateConfirm = () => {
  if (selectedDate.value) errors.value.date = undefined
  isDateSheetOpen.value = false
}

const validate = () => {
  errors.value = {}
  if (!selectedCountry.value) errors.value.country = '국가를 선택해 주세요.'
  if (!selectedDate.value) errors.value.date = '시작 날짜를 선택해 주세요.'
  return Object.keys(errors.value).length === 0
}

const onSubmit = () => {
  if (!validate()) return

  if (order.value && selectedDate.value) {
    const start = new Date(
      selectedDate.value.year,
      selectedDate.value.month - 1,
      selectedDate.value.day,
    )
    const end = addDays(start, order.value.planDataDuration)

    // startTime = -24: backend createUTCDateTime 이 addHours(midnight, -24) 로
    // timeToBeActivatedInUTC 를 (선택일 -1 day) 00:00 현지시각으로 저장 → eSIM
    // 사전 활성화 버퍼. startDate 는 사용자가 선택한 날짜 그대로.
    const updatedOrder: Order = {
      ...order.value,
      startDate: format(start, 'yyyy-MM-dd'),
      endDate: format(end, 'yyyy-MM-dd'),
      startTime: -24,
      startTimeZone: getTimeZone(),
      startCountry: selectedCountry.value,
    }
    orderStore.setSingleOrder(updatedOrder)
    isPolicyAgreed.value = false
    isConfirmOrderVisible.value = true
  } else {
    isNoOrderAlertVisible.value = true
    setTimeout(() => {
      isNoOrderAlertVisible.value = false
      router.push(`/verify/${orderId.value}`)
    }, 3000)
  }
}

const onConfirm = async () => {
  if (isSubmitting.value || !isPolicyAgreed.value) return
  isSubmitting.value = true
  isConfirmOrderVisible.value = false
  isIssueQrCodesVisible.value = true

  if (!order.value) {
    isSubmitting.value = false
    isIssueQrCodesVisible.value = false
    isNoOrderAlertVisible.value = true
    setTimeout(() => {
      isNoOrderAlertVisible.value = false
      router.push(`/verify/${orderId.value}`)
    }, 3000)
    return
  }

  await new Promise((resolve) => setTimeout(resolve, 2000))

  try {
    const verifyResponse = await api.verifyOrder({
      orderId: orderId.value,
      phoneNumber: order.value.receiverPhoneNumber,
      fullName: order.value.receiverName,
    })
    const { verified, cancelled } = verifyResponse

    if (verified && !cancelled) {
      const activateResponse = await api.activateOrder(orderStore.singleOrder!)
      const { verified: activateVerified, details } = activateResponse
      if (activateVerified && details) {
        isIssueQrCodesVisible.value = false
        orderStore.setSingleOrder(details[0])

        const updatedOrders = await api.verifyOrder({
          orderId: orderId.value,
          phoneNumber: order.value.receiverPhoneNumber,
          fullName: order.value.receiverName,
        })
        if (updatedOrders.details) orderStore.setOrders(updatedOrders.details)

        router.push(`/view/${orderId.value}`)
      } else {
        isSubmitting.value = false
        isIssueQrCodesVisible.value = false
        isNoOrderAlertVisible.value = true
        setTimeout(() => {
          isNoOrderAlertVisible.value = false
          router.push(`/verify/${orderId.value}`)
        }, 2000)
      }
    } else if (verified && cancelled) {
      isSubmitting.value = false
      isIssueQrCodesVisible.value = false
      isCancelledOrderVisible.value = true
      setTimeout(() => {
        isCancelledOrderVisible.value = false
        router.push(`/verify/${orderId.value}`)
      }, 2000)
    } else {
      isSubmitting.value = false
      isIssueQrCodesVisible.value = false
      isNoOrderAlertVisible.value = true
      setTimeout(() => {
        isNoOrderAlertVisible.value = false
        router.push(`/verify/${orderId.value}`)
      }, 2000)
    }
  } catch (error) {
    console.error(error)
    isSubmitting.value = false
    isIssueQrCodesVisible.value = false
    isNoOrderAlertVisible.value = true
    setTimeout(() => {
      isNoOrderAlertVisible.value = false
      router.push(`/verify/${orderId.value}`)
    }, 3000)
  }
}

onMounted(() => {
  if (!order.value) {
    isNoOrderAlertVisible.value = true
    setTimeout(() => {
      isNoOrderAlertVisible.value = false
      router.push(`/verify/${orderId.value}`)
    }, 3000)
  } else if (order.value.esims && order.value.esims.length > 0) {
    router.push(`/details/${orderId.value}`)
  }
})
</script>

<template>
  <div class="select-date-page">
    <div class="select-date-page__top">
      <NStepProgress :step="3" :total="4" label="사용 일시" />
    </div>

    <div class="select-date-page__heading">
      <NPageHeading
        eyebrow="eSIM QR 코드 발급"
        :title="`사용 시작 날짜를\n선택해 주세요`"
        :description="`현지에 도착하는 날짜를 골라 주시면\n그날부터 회선이 자동으로 켜져요.`"
      />
    </div>

    <div class="select-date-page__chip-row">
      <NInfoChip label="주문번호" :value="String(orderId)">
        <template #icon>
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <rect x="3" y="4" width="18" height="16" rx="2" />
            <path d="M8 2v4M16 2v4M3 10h18" />
          </svg>
        </template>
      </NInfoChip>
      <NInfoChip v-if="order" :value="order.planNameKr">
        <template #icon>
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M2 12h20M12 2a15 15 0 0 1 0 20M12 2a15 15 0 0 0 0 20" />
            <circle cx="12" cy="12" r="10" />
          </svg>
        </template>
      </NInfoChip>
    </div>

    <div class="select-date-page__fields">
      <div class="select-date-page__field-wrap">
        <NFieldCard
          label="시작 국가"
          :value="countryLabel"
          placeholder="국가를 선택해 주세요"
          :active="!!selectedCountry"
          :error="!!errors.country"
          @click="isCountrySheetOpen = true"
        />
        <p v-if="errors.country" class="select-date-page__err">{{ errors.country }}</p>
      </div>

      <div class="select-date-page__field-wrap">
        <NFieldCard
          label="시작 날짜"
          :value="startDateLabel"
          placeholder="날짜를 선택해 주세요"
          :active="!!selectedDate"
          :error="!!errors.date"
          @click="isDateSheetOpen = true"
        />
        <p v-if="errors.date" class="select-date-page__err">{{ errors.date }}</p>
      </div>
    </div>

    <div v-if="selectedDate" class="select-date-page__preview">
      <NHighlightCard>
        <template #icon>
          <svg
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2.2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M12 8v4l3 2" />
            <circle cx="12" cy="12" r="10" />
          </svg>
        </template>
        eSIM 사용 예상 기간은
        <b style="color: var(--color-primary-700)">{{ startDateLabel }} ~ {{ endDateLabel }}</b>
        이에요.
      </NHighlightCard>
    </div>

    <div class="select-date-page__notes">
      <NTrustNote>
        <template #icon>
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2.2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <path d="M12 7v5l3 2" />
          </svg>
        </template>
        <b style="color: #111827">사용 일수는 첫 연결 시점부터 24시간 단위로 차감돼요.</b><br />
        현지에 도착해 처음 회선이 연결된 순간부터 24시간이 지나면 1일이 차감돼요. 선택한 날짜에
        도착하지 않아도 실제 연결 전까지는 사용일이 줄지 않아요.
      </NTrustNote>
      <div style="height: 8px" />
      <NTrustNote>
        <template #icon>
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2.2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <path d="M2 12h20" />
            <path
              d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"
            />
          </svg>
        </template>
        <b style="color: #111827">다국가 이심은 자동 로밍으로 그대로 사용할 수 있어요.</b><br />
        한 번 개통된 다음에는 포함된 국가들을 오가도 추가 설치나 설정 변경 없이 자동으로 연결돼요.
      </NTrustNote>
    </div>

    <div class="select-date-page__cta">
      <NButton
        type="button"
        variant="primary"
        size="xl"
        full-width
        :disabled="isSubmitting"
        @click="onSubmit"
      >
        QR 코드 발행하기
      </NButton>
    </div>

    <!-- Country bottom sheet -->
    <NBottomSheet v-model="isCountrySheetOpen" title="시작 국가 선택">
      <div class="select-date-page__sheet-list">
        <button
          v-for="c in combinedCountries"
          :key="c.iso"
          type="button"
          class="select-date-page__sheet-row"
          :class="{ 'select-date-page__sheet-row--active': selectedCountry === c.kr }"
          @click="onCountrySelect(c.kr)"
        >
          <span class="select-date-page__sheet-row-main">{{ c.kr }}</span>
          <span class="select-date-page__sheet-row-sub">{{ c.timeZone }}</span>
        </button>
      </div>
    </NBottomSheet>

    <!-- Date bottom sheet -->
    <NBottomSheet v-model="isDateSheetOpen" title="시작 날짜 선택">
      <div class="select-date-page__cal">
        <NDurationCalendar v-model="selectedDate" :duration="order?.planDataDuration || 0" />
      </div>
      <template #footer>
        <NButton variant="primary" size="xl" full-width @click="onDateConfirm"> 선택 완료 </NButton>
      </template>
    </NBottomSheet>

    <!-- Confirm summary -->
    <NAlertDialog
      v-model="isConfirmOrderVisible"
      title="이 내용으로 발급할까요?"
      color="primary"
      :closable="false"
      :width="340"
    >
      <div v-if="order" class="select-date-page__confirm">
        <div class="select-date-page__confirm-row">
          <span>상품</span><b>{{ order.planNameKr }}</b>
        </div>
        <div class="select-date-page__confirm-row">
          <span>시작 국가</span><b>{{ selectedCountry }}</b>
        </div>
        <div class="select-date-page__confirm-row">
          <span>시작 날짜</span><b>{{ startDateLabel }}</b>
        </div>
        <div class="select-date-page__confirm-row">
          <span>사용 기간</span><b>{{ order.planDataDuration }}일</b>
        </div>
        <div class="select-date-page__confirm-row">
          <span>수량</span><b>{{ order.quantity }}개</b>
        </div>
      </div>
      <div class="select-date-page__confirm-policy">
        <svg
          class="select-date-page__confirm-policy-icon"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path
            d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"
          />
          <line x1="12" y1="9" x2="12" y2="13" />
          <line x1="12" y1="17" x2="12.01" y2="17" />
        </svg>
        <p>
          <b>발급 후에는 취소와 환불이 불가해요.</b><br />
          사용하실 기기가 eSIM 지원 기기인지 발급 전에 꼭 확인해 주세요.
        </p>
      </div>
      <div class="select-date-page__confirm-agree">
        <NCheckbox v-model="isPolicyAgreed" label="위 내용을 확인했고 동의해요" />
      </div>
      <template #actions>
        <div class="select-date-page__confirm-actions">
          <NButton variant="secondary" @click="isConfirmOrderVisible = false">뒤로</NButton>
          <NButton
            variant="primary"
            :disabled="isSubmitting || !isPolicyAgreed"
            @click="onConfirm"
          >
            발급하기
          </NButton>
        </div>
      </template>
    </NAlertDialog>

    <NLoaderDialog
      v-model="isIssueQrCodesVisible"
      title="QR 코드를 발급하고 있어요"
      description="잠시만 기다려주세요…"
    />

    <NAlertDialog
      v-model="isNoOrderAlertVisible"
      title="주문 정보를 찾을 수 없어요"
      color="warning"
      :closable="false"
    >
      <p class="select-date-page__dialog-desc">
        주문번호를 다시 확인해 주세요.<br />본인 확인 페이지로 돌아갈게요.
      </p>
    </NAlertDialog>

    <NAlertDialog
      v-model="isCancelledOrderVisible"
      title="이미 취소된 주문이에요"
      color="warning"
      :closable="false"
    >
      <p class="select-date-page__dialog-desc">
        취소된 주문은 발급할 수 없어요.<br />본인 확인 페이지로 돌아갈게요.
      </p>
    </NAlertDialog>
  </div>
</template>

<style scoped>
.select-date-page {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  padding: 20px 24px 32px;
  background: #ffffff;
}

.select-date-page__heading {
  margin-top: 28px;
}

.select-date-page__chip-row {
  margin-top: 18px;
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.select-date-page__fields {
  margin-top: 28px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.select-date-page__field-wrap {
  display: flex;
  flex-direction: column;
}

.select-date-page__err {
  margin: 6px 0 0 4px;
  font-size: 12px;
  color: var(--color-error-500, #ef4444);
}

.select-date-page__preview {
  margin-top: 20px;
}

.select-date-page__notes {
  margin-top: 16px;
}

.select-date-page__cta {
  margin-top: auto;
  padding-top: 32px;
}

.select-date-page__sheet-list {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.select-date-page__sheet-row {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  width: 100%;
  padding: 14px 12px;
  border: none;
  background: transparent;
  border-radius: 12px;
  cursor: pointer;
  text-align: left;
  transition: background 120ms ease;
}

.select-date-page__sheet-row:hover {
  background: #f8fafc;
}

.select-date-page__sheet-row--active {
  background: var(--color-primary-50, #f3efff);
}

.select-date-page__sheet-row-main {
  font-size: 15px;
  font-weight: 600;
  color: #111827;
}

.select-date-page__sheet-row-sub {
  font-size: 11.5px;
  color: #94a3b8;
}

.select-date-page__cal {
  padding: 0 4px 12px;
}

.select-date-page__confirm {
  display: flex;
  flex-direction: column;
  gap: 10px;
  width: 100%;
  background: #f9fafb;
  border-radius: 14px;
  padding: 14px;
  font-size: 13px;
}

.select-date-page__confirm-row {
  display: flex;
  justify-content: space-between;
}

.select-date-page__confirm-row span {
  color: #6b7280;
}

.select-date-page__confirm-row b {
  font-weight: 600;
  color: #111827;
}

.select-date-page__confirm-policy {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  width: 100%;
  margin-top: 10px;
  padding: 12px 14px;
  background: #fef2f2;
  border-radius: 12px;
  font-size: 12px;
  line-height: 1.55;
  color: #6b7280;
  text-align: left;
}

.select-date-page__confirm-policy-icon {
  flex-shrink: 0;
  margin-top: 1px;
  color: #dc2626;
}

.select-date-page__confirm-policy b {
  font-weight: 600;
  color: #dc2626;
}

.select-date-page__confirm-agree {
  width: 100%;
  margin-top: 10px;
  display: flex;
  justify-content: flex-start;
  text-align: left;
  font-size: 13px;
}

.select-date-page__confirm-actions {
  display: grid;
  grid-template-columns: 1fr 2fr;
  gap: 8px;
  width: 100%;
}

.select-date-page__dialog-desc {
  margin: -6px 0 0;
  font-size: 13px;
  color: #6b7280;
  text-align: center;
  line-height: 1.55;
}
</style>

// apps/mobile/src/app/select-date/[orderId].tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { useLocalSearchParams, useRouter } from 'expo-router'

import {
  NAlertDialog,
  NBottomSheet,
  NButton,
  NCheckbox,
  NDurationCalendar,
  NFieldCard,
  NHighlightCard,
  NInfoChip,
  NLoaderDialog,
  NPageHeading,
  NStepProgress,
  NTrustNote,
  type CalDate,
} from '@imjohnkoo/design-mobile'

import { FlowScreen, FlowSpacer } from '@/components/flow-screen'
import { api } from '@/lib/api'
import { addDays, calDateToDate, formatDateLabel, toIsoDateString } from '@/lib/date'
import { useOrderStore } from '@/lib/order-store'
import type { Order } from '@/lib/types'

export default function SelectDateScreen() {
  const router = useRouter()
  const { orderId: orderIdParam } = useLocalSearchParams<{ orderId: string }>()
  const orderId = Number(orderIdParam)
  const orderStore = useOrderStore()

  const order = orderStore.singleOrder

  const combinedCountries = useMemo(() => {
    if (!order) return []
    return order.planCountriesKr.map((country, index) => ({
      kr: country,
      en: order.planCountriesEng[index] || '',
      iso: order.planCountriesIso[index] || '',
      timeZone: order.timeZones[index] || '',
    }))
  }, [order])

  const [selectedCountry, setSelectedCountry] = useState('')
  const [selectedDate, setSelectedDate] = useState<CalDate | null>(null)
  const [errors, setErrors] = useState<{ country?: string; date?: string }>({})

  const [isCountrySheetOpen, setIsCountrySheetOpen] = useState(false)
  const [isDateSheetOpen, setIsDateSheetOpen] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isPolicyAgreed, setIsPolicyAgreed] = useState(false)
  const [isIssueQrCodesVisible, setIsIssueQrCodesVisible] = useState(false)
  const [isNoOrderAlertVisible, setIsNoOrderAlertVisible] = useState(false)
  const [isCancelledOrderVisible, setIsCancelledOrderVisible] = useState(false)
  // 확인 다이얼로그에 표시/전송할 스냅샷 — setState 비동기와 무관하게 고정
  const [confirmOrder, setConfirmOrder] = useState<Order | null>(null)

  const timers = useRef<ReturnType<typeof setTimeout>[]>([])
  useEffect(
    () => () => {
      timers.current.forEach(clearTimeout)
    },
    [],
  )

  const backToVerify = (hideDialog: () => void, delay: number) => {
    timers.current.push(
      setTimeout(() => {
        hideDialog()
        router.replace({ pathname: '/verify/[orderId]', params: { orderId: orderIdParam } })
      }, delay),
    )
  }

  useEffect(() => {
    if (!order) {
      setIsNoOrderAlertVisible(true)
      backToVerify(() => setIsNoOrderAlertVisible(false), 3000)
    } else if (order.esims && order.esims.length > 0) {
      router.replace({ pathname: '/details/[orderId]', params: { orderId: orderIdParam } })
    }
    // 최초 진입 가드 — client select-date 페이지 onMounted 와 동일 정책
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const startDateLabel = selectedDate ? formatDateLabel(calDateToDate(selectedDate)) : ''
  const endDateLabel =
    selectedDate && order
      ? formatDateLabel(addDays(calDateToDate(selectedDate), order.planDataDuration))
      : ''

  const countryLabel = useMemo(() => {
    if (!selectedCountry) return ''
    const c = combinedCountries.find((c) => c.kr === selectedCountry)
    return c ? `${c.kr} · ${c.timeZone}` : selectedCountry
  }, [selectedCountry, combinedCountries])

  const getTimeZone = () =>
    combinedCountries.find((c) => c.kr === selectedCountry)?.timeZone || 'Asia/Seoul'

  const onCountrySelect = (kr: string) => {
    setSelectedCountry(kr)
    setIsCountrySheetOpen(false)
    setErrors((e) => ({ ...e, country: undefined }))
  }

  const onDateConfirm = () => {
    if (selectedDate) setErrors((e) => ({ ...e, date: undefined }))
    setIsDateSheetOpen(false)
  }

  const validate = () => {
    const next: typeof errors = {}
    if (!selectedCountry) next.country = '국가를 선택해 주세요.'
    if (!selectedDate) next.date = '시작 날짜를 선택해 주세요.'
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const onSubmit = () => {
    if (!validate()) return
    if (!order || !selectedDate) {
      setIsNoOrderAlertVisible(true)
      backToVerify(() => setIsNoOrderAlertVisible(false), 3000)
      return
    }

    const start = calDateToDate(selectedDate)
    const end = addDays(start, order.planDataDuration)

    // startTime = -24: backend createUTCDateTime 이 addHours(midnight, -24) 로
    // timeToBeActivatedInUTC 를 (선택일 -1 day) 00:00 현지시각으로 저장 → eSIM
    // 사전 활성화 버퍼. startDate 는 사용자가 선택한 날짜 그대로.
    const updatedOrder: Order = {
      ...order,
      startDate: toIsoDateString(start),
      endDate: toIsoDateString(end),
      startTime: -24,
      startTimeZone: getTimeZone(),
      startCountry: selectedCountry,
    }
    orderStore.setSingleOrder(updatedOrder)
    setConfirmOrder(updatedOrder)
    setIsPolicyAgreed(false)
  }

  const onConfirm = async () => {
    if (isSubmitting || !isPolicyAgreed || !confirmOrder) return
    setIsSubmitting(true)
    const target = confirmOrder
    setConfirmOrder(null)
    setIsIssueQrCodesVisible(true)

    try {
      const verifyResponse = await api.verifyOrder({
        orderId,
        phoneNumber: target.receiverPhoneNumber,
        fullName: target.receiverName,
      })
      const { verified, cancelled } = verifyResponse

      if (verified && !cancelled) {
        const activateResponse = await api.activateOrder(target)
        const { verified: activateVerified, details } = activateResponse
        if (activateVerified && details && details[0]) {
          orderStore.setSingleOrder(details[0])

          const updatedOrders = await api.verifyOrder({
            orderId,
            phoneNumber: target.receiverPhoneNumber,
            fullName: target.receiverName,
          })
          if (updatedOrders.details) orderStore.setOrders(updatedOrders.details)

          setIsIssueQrCodesVisible(false)
          setIsSubmitting(false)
          router.push({ pathname: '/view/[orderId]', params: { orderId: orderIdParam } })
        } else {
          setIsSubmitting(false)
          setIsIssueQrCodesVisible(false)
          setIsNoOrderAlertVisible(true)
          backToVerify(() => setIsNoOrderAlertVisible(false), 2000)
        }
      } else if (verified && cancelled) {
        setIsSubmitting(false)
        setIsIssueQrCodesVisible(false)
        setIsCancelledOrderVisible(true)
        backToVerify(() => setIsCancelledOrderVisible(false), 2000)
      } else {
        setIsSubmitting(false)
        setIsIssueQrCodesVisible(false)
        setIsNoOrderAlertVisible(true)
        backToVerify(() => setIsNoOrderAlertVisible(false), 2000)
      }
    } catch (error) {
      console.error(error)
      setIsSubmitting(false)
      setIsIssueQrCodesVisible(false)
      setIsNoOrderAlertVisible(true)
      backToVerify(() => setIsNoOrderAlertVisible(false), 3000)
    }
  }

  return (
    <FlowScreen>
      <NStepProgress step={3} total={4} label="사용 일시" />

      <View style={styles.heading}>
        <NPageHeading
          eyebrow="eSIM QR 코드 발급"
          title={'사용 시작 날짜를\n선택해 주세요'}
          description={'현지에 도착하는 날짜를 골라 주시면\n그날부터 회선이 자동으로 켜져요.'}
        />
      </View>

      <View style={styles.chipRow}>
        <NInfoChip label="주문번호" value={String(orderId)} />
        {order && <NInfoChip value={order.planNameKr} />}
      </View>

      <View style={styles.fields}>
        <View>
          <NFieldCard
            label="시작 국가"
            value={countryLabel}
            placeholder="국가를 선택해 주세요"
            active={!!selectedCountry}
            error={!!errors.country}
            onPress={() => setIsCountrySheetOpen(true)}
          />
          {errors.country && <Text style={styles.err}>{errors.country}</Text>}
        </View>

        <View>
          <NFieldCard
            label="시작 날짜"
            value={startDateLabel}
            placeholder="날짜를 선택해 주세요"
            active={!!selectedDate}
            error={!!errors.date}
            onPress={() => setIsDateSheetOpen(true)}
          />
          {errors.date && <Text style={styles.err}>{errors.date}</Text>}
        </View>
      </View>

      {selectedDate && (
        <View style={styles.preview}>
          <NHighlightCard>
            <Text style={styles.previewText}>
              eSIM 사용 예상 기간은{' '}
              <Text style={styles.previewStrong}>
                {startDateLabel} ~ {endDateLabel}
              </Text>{' '}
              이에요.
            </Text>
          </NHighlightCard>
        </View>
      )}

      <View style={styles.notes}>
        <NTrustNote title="사용 일수는 첫 연결 시점부터 24시간 단위로 차감돼요.">
          {'현지에 도착해 처음 회선이 연결된 순간부터 24시간이 지나면 1일이 차감돼요. 선택한 날짜에 도착하지 않아도 실제 연결 전까지는 사용일이 줄지 않아요.'}
        </NTrustNote>
        <View style={styles.noteGap} />
        <NTrustNote title="다국가 이심은 자동 로밍으로 그대로 사용할 수 있어요.">
          {'한 번 개통된 다음에는 포함된 국가들을 오가도 추가 설치나 설정 변경 없이 자동으로 연결돼요.'}
        </NTrustNote>
      </View>

      <FlowSpacer />

      <View style={styles.cta}>
        <NButton variant="primary" size="xl" fullWidth disabled={isSubmitting} onPress={onSubmit}>
          QR 코드 발행하기
        </NButton>
      </View>

      {/* 시작 국가 bottom sheet */}
      <NBottomSheet
        visible={isCountrySheetOpen}
        onClose={() => setIsCountrySheetOpen(false)}
        title="시작 국가 선택"
      >
        <View style={styles.sheetList}>
          {combinedCountries.map((c) => (
            <TouchableOpacity
              key={c.iso || c.kr}
              style={[styles.sheetRow, selectedCountry === c.kr && styles.sheetRowActive]}
              onPress={() => onCountrySelect(c.kr)}
              activeOpacity={0.7}
            >
              <Text style={styles.sheetRowMain}>{c.kr}</Text>
              <Text style={styles.sheetRowSub}>{c.timeZone}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </NBottomSheet>

      {/* 시작 날짜 bottom sheet */}
      <NBottomSheet
        visible={isDateSheetOpen}
        onClose={() => setIsDateSheetOpen(false)}
        title="시작 날짜 선택"
        footer={
          <NButton variant="primary" size="xl" fullWidth onPress={onDateConfirm}>
            선택 완료
          </NButton>
        }
      >
        <NDurationCalendar
          value={selectedDate}
          onChange={setSelectedDate}
          duration={order?.planDataDuration || 0}
        />
      </NBottomSheet>

      {/* 발급 확인 */}
      <NAlertDialog
        visible={!!confirmOrder}
        title="이 내용으로 발급할까요?"
        color="primary"
        closable={false}
        width={340}
        actions={
          <View style={styles.confirmActions}>
            <View style={styles.confirmBack}>
              <NButton variant="secondary" fullWidth onPress={() => setConfirmOrder(null)}>
                뒤로
              </NButton>
            </View>
            <View style={styles.confirmGo}>
              <NButton
                variant="primary"
                fullWidth
                disabled={isSubmitting || !isPolicyAgreed}
                onPress={onConfirm}
              >
                발급하기
              </NButton>
            </View>
          </View>
        }
      >
        {confirmOrder && (
          <View style={styles.confirmBox}>
            <View style={styles.confirmRow}>
              <Text style={styles.confirmKey}>상품</Text>
              <Text style={styles.confirmVal}>{confirmOrder.planNameKr}</Text>
            </View>
            <View style={styles.confirmRow}>
              <Text style={styles.confirmKey}>시작 국가</Text>
              <Text style={styles.confirmVal}>{confirmOrder.startCountry}</Text>
            </View>
            <View style={styles.confirmRow}>
              <Text style={styles.confirmKey}>시작 날짜</Text>
              <Text style={styles.confirmVal}>{startDateLabel}</Text>
            </View>
            <View style={styles.confirmRow}>
              <Text style={styles.confirmKey}>사용 기간</Text>
              <Text style={styles.confirmVal}>{confirmOrder.planDataDuration}일</Text>
            </View>
            <View style={styles.confirmRow}>
              <Text style={styles.confirmKey}>수량</Text>
              <Text style={styles.confirmVal}>{confirmOrder.quantity}개</Text>
            </View>
          </View>
        )}
        <View style={styles.confirmPolicy}>
          <Text style={styles.confirmPolicyTitle}>발급 후에는 취소와 환불이 불가해요.</Text>
          <Text style={styles.confirmPolicyBody}>
            사용하실 기기가 eSIM 지원 기기인지 발급 전에 꼭 확인해 주세요.
          </Text>
        </View>
        <View style={styles.confirmAgree}>
          <NCheckbox
            checked={isPolicyAgreed}
            onToggle={setIsPolicyAgreed}
            label="위 내용을 확인했고 동의해요"
          />
        </View>
      </NAlertDialog>

      <NLoaderDialog
        visible={isIssueQrCodesVisible}
        title="QR 코드를 발급하고 있어요"
        description="잠시만 기다려주세요…"
      />

      <NAlertDialog
        visible={isNoOrderAlertVisible}
        title="주문 정보를 찾을 수 없어요"
        color="warning"
        closable={false}
      >
        {'주문번호를 다시 확인해 주세요.\n본인 확인 페이지로 돌아갈게요.'}
      </NAlertDialog>

      <NAlertDialog
        visible={isCancelledOrderVisible}
        title="이미 취소된 주문이에요"
        color="warning"
        closable={false}
      >
        {'취소된 주문은 발급할 수 없어요.\n본인 확인 페이지로 돌아갈게요.'}
      </NAlertDialog>
    </FlowScreen>
  )
}

const styles = StyleSheet.create({
  heading: {
    marginTop: 28,
  },
  chipRow: {
    marginTop: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  fields: {
    marginTop: 28,
    gap: 10,
  },
  err: {
    marginTop: 6,
    marginLeft: 4,
    fontSize: 12,
    color: '#ef4444',
  },
  preview: {
    marginTop: 20,
  },
  previewText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#374151',
  },
  previewStrong: {
    fontWeight: '700',
    color: '#4c1d95',
  },
  notes: {
    marginTop: 16,
  },
  noteGap: {
    height: 8,
  },
  cta: {
    paddingTop: 32,
  },
  sheetList: {
    gap: 2,
  },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  sheetRowActive: {
    backgroundColor: '#f3efff',
  },
  sheetRowMain: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
  },
  sheetRowSub: {
    fontSize: 11.5,
    color: '#94a3b8',
  },
  confirmBox: {
    width: '100%',
    backgroundColor: '#f9fafb',
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  confirmRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  confirmKey: {
    fontSize: 13,
    color: '#6b7280',
  },
  confirmVal: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#111827',
    textAlign: 'right',
  },
  confirmPolicy: {
    width: '100%',
    marginTop: 10,
    padding: 13,
    backgroundColor: '#fef2f2',
    borderRadius: 12,
  },
  confirmPolicyTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#dc2626',
    marginBottom: 4,
  },
  confirmPolicyBody: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
  },
  confirmAgree: {
    width: '100%',
    marginTop: 12,
    alignItems: 'flex-start',
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 8,
  },
  confirmBack: {
    flex: 1,
  },
  confirmGo: {
    flex: 2,
  },
})
